### ISSUE TITLE
blackboard.png image is not being applied to all slides

### ISSUE THREAD

**Issue by kyle-messier** [schochastics/quarto-blackboard-theme#2]
Hi, the blackboard.png is only being applied to the title slide for me. Any suggestions for modifications to the scss or _extensions.yml to apply to all slides?

**Comment by kyle-messier** [comment]
Ok, perhaps an ad-hoc fix, but was able to add directly to each slide:

```r
## Slide Title {background-image="_extensions/blackboard/blackboard.png"}

`

**Comment by schochastics** [comment]
hmm this seems like a quarto update is responsible for that. I will try to adapt the template

**Comment by schochastics** [comment]
hmm turns out it still works for me. Can you provide a reproducible example, or talk through what you did that caused the problem?

**Comment by kyle-messier** [comment]
It is entirely possible that it is because of my green-ness and naïveté on how to implement the quarto templates. I was having bad luck with the installation via `quarto use template xxxx`. Instead my approach was to clone the repo and change the template.qmd to my working document.

**Comment by schochastics** [comment]
So the `quarto use template` does work for me. cloning does not work, because there is still some hardcoded copy paste in the template that i cannot resolve, which only work with `quarto use template`. Can you tell me what your issue with that is?

**Comment by kyle-messier** [comment]
My ignorance - I've been using Quarto through Rstudio and didn't realize I needed to also install Quarto as stand alone software. You can chalk this one up to the learning curve - will close this issue. Thanks!
