### ISSUE TITLE
Second level sub list item

### ISSUE THREAD

**Issue by bsgallih12** [schochastics/quarto-blackboard-theme#3]
Hello,

I like the dot.png image that becomes a bullet point for level 1 list points. However when I do it for a second level list point, I get a white square before the dot.png image. Is there a way around this?

**Comment by schochastics** [comment]
Thanks for flagging this. I think I fixed it. Can you try with the new version

**Comment by bsgallih12** [comment]
It works great. Thanks! Love the theme. Have you created any others

**Comment by schochastics** [comment]
Thanks! No, this is the only one I made.
